---
pool: 
  name: "Azure Pipelines"
  vmImage: 'ubuntu-latest'

pr:
  - azuredevops
parameters:
  - name: mavenPomFile
    displayName: pom file
    type: string
    default: 'pom.xml'
  - name: goal
    displayName: maven goal
    type: string
    default: 'package'
    values: 
      - 'package'
      - 'build'
      - 'clean'
      - 'compile'
  - name: jdkVersion
    displayName: java version
    type: string
    default: '1.17'
  - name: PathtoPublish
    displayName: path to publish
    type: string
    default: 'target/spring-petclinic-*.jar'
  - name: mavenAuthenticateFeed
    displayName: Authentic to maven feed
    type: boolean
    default: true

jobs:
  - job: buildNdPush
    displayName: "build and push"
    steps: 
      - task: Maven@3
        inputs:
          mavenPOMFile: "${{ parameters.mavenPomFile }}"
          goals: "${{ parameters.goal }}"
          publishJUnitResults: yes
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: "${{ parameters.jdkVersion }}"  
          mavenAuthenticateFeed: "${{ parameters.mavenAuthenticateFeed }}"


  